site:
  name: 'Ecosystem Restoration Alliance Indian Ocean'
  site: 'https://era-indianocean.org'
  base: '/'
  trailingSlash: false
  # googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

metadata:
  title:
    default: Ecosystem Restoration Alliance Indian Ocean
    template: '%s — Ecosystem Restoration Alliance Indian Ocean'
  description: 'Ecosystem Restoration Alliance Indian Ocean (ERA IO) is the only non-profitable organisation (NGO) in Mauritius that exclusively specialises in bat research, conservation and bat-ecosystem interactions.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Ecosystem Restoration Alliance Indian Ocean
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@eraindianocean'
    site: '@eraindianocean'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
